import './globals.css';
import Image from 'next/image';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, onViewChange }) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <main className="bg-white">{children}</main>
      </body>
    </html>
  )
}
